apiVersion: apps/v1
kind: Deployment
metadata:
    name: kp_poc
    labels:
        app:kp_app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: kp_app
    template:
        metadata:
            name: kp_pod
            labels:
                app: kp_app
        spec:
            containers:
                - name: nginx-container
                   image: nginx
